# Generated by Django 5.1.13 on 2025-10-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
                ('interest', models.TextField()),
                ('bucket_list', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'About Me (Singleton)',
            },
        ),
    ]
