# Generated by Django 5.1.13 on 2025-10-27 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='poem',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
